### ISSUE TITLE
[Server Fatal] System.IndexOutOfRangeException [1.18.14 MP]

### ISSUE THREAD

**Issue by WickedSchnitzel** [Quacksol/VSInstruments#5]
[Server Fatal] System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.String.get_Chars(Int32 index)
   at instruments.ABCParser.ParseFile()
   at instruments.ABCParser.Update(Single dt)
   at instruments.ABCParsers.Update(ICoreServerAPI sapi, Single dt)
   at instruments.InstrumentModServer.OnServerGameTick(Single dt)
   at Vintagestory.Common.EventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Common\EventManager.cs:line 59
   at Vintagestory.Server.CoreServerEventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Server\ServerEventManager.cs:line 124
   at Vintagestory.Server.ServerMain.Process() in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Server\ServerMain.cs:line 881

**Comment by WickedSchnitzel** [comment]
still crahing in v1.2.6 with

Running on 64 bit Windows 10.0.19045.0 with 16146 MB RAM
Game Version: v1.19.3 (Stable)
03/02/2024 13:04:26: Critical error occurred in the following mod: vsinstruments@1.2.6
Loaded Mods: weaponpacka@1.3.1, bettercrates@1.7.0, Ceramos@0.4.3, chiseltools@1.10.1, extrachests@1.8.0, fixedpaths@1.0.1, flourbags@1.0.2, giantgouramis@1.0.2, millwright@1.1.4, moreicons_cs@1.1.0, peacockbasses@1.1.2, primitivesurvival@3.4.5, spyglass@0.5.0, Swordz@1.1.4, thecritterpack@0.8.3, translocatorengineeringredux@1.4.9, truesunfishes@1.1.2, game@1.19.3, alphaweaponpackfix@1.0.0, ancienttools@1.5.12, barbershop@0.4.0, beehivekiln@1.5.1, betterjonasdevices@1.1.0, betterruins@0.3.2, carryon@1.7.4, commonlib@2.3.2, fairplayguardian@1.1.7, furniturelibrary@1.0.11, herbarium@1.0.4, icecold@0.5.1, sailboat@1.2.7, meteoricexpansion@1.2.5, morepiles@1.5.0, moreplaster@1.0.1, petai@2.2.3, rivers@2.3.0, simplestep@1.1.4, steadycam@1.2.0, stonebakeoven@1.1.3, tentbag@1.0.3, th3dungeon@0.2.1-rc.1, vinconomy@0.2.1, creative@1.19.3, vsinstruments@1.2.6, vsquest@1.2.0, survival@1.19.3, workbenchexpansion@1.8.0, xlib119@0.7.4-dev.119, awearablelight@1.1.1, cob2@1.5.6, em@2.5.0, outerspacetunesmaster@1.0.0, outerspacetunesvolume1@1.0.0, outerspacetunesvolume2@1.0.0, playercorpse@1.9.0, rifteye@0.3.4, simplewinddirection@1.0.2, stonequarry@3.2.1, wildcraftfruit@1.0.1, wolftaming@2.0.2, xskills119@0.7.5-dev.1191, bricklayers@2.5.0-pre.2, cob@1.5.9, vsvillagecob@0.1.9
System.NullReferenceException: Object reference not set to an instance of an object.
   at instruments.InstrumentModClient.StopSounds(ABCStopFromServer serverPacket) in C:\Users\Bane\Documents\vs\Mods\mods\vsinstruments\vsinstruments\src\Main.cs:line 331
   at Vintagestory.Client.NoObf.NetworkChannel.<>c__DisplayClass12_0`1.<SetMessageHandler>b__0(Packet_CustomPacket p) in VintagestoryLib\Client\API\NetworkChannel.cs:line 74
   at Vintagestory.Client.NoObf.NetworkAPI.HandleCustomPacket(Packet_Server packet) in VintagestoryLib\Client\API\NetworkAPI.cs:line 95
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 769
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 200
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 675
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 650
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 318
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries for Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 03/02/2024 12:38:47, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.3.0, time stamp: 0x65310000
Faulting module name: KERNELBASE.dll, version: 10.0.19041.3930, time stamp: 0x9141f979
Exception code: 0xe0434352
Fault offset: 0x000000000002cf19
Faulting process ID: 0x46dc
Faulting application start time: 0x01da560d91dc2ece
Faulting application path: D:\Vintagestory\Vintagestory.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report ID: 13996d3f-4f63-4245-8404-16a29d3dbeb9
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 02/02/2024 14:03:52, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.3.0, time stamp: 0x65310000
Faulting module name: KERNELBASE.dll, version: 10.0.19041.3930, time stamp: 0x9141f979
Exception code: 0xe0434352
Fault offset: 0x000000000002cf19
Faulting process ID: 0x5500
Faulting application start time: 0x01da55577cfb7cdc
Faulting application path: D:\Vintagestory\Vintagestory.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report ID: 71111c30-541a-42da-a616-04fc13e78acb
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 01/02/2024 22:41:50, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.3.0, time stamp: 0x65310000
Faulting module name: KERNELBASE.dll, version: 10.0.19041.3930, time stamp: 0x9141f979
Exception code: 0xe0434352
Fault offset: 0x000000000002cf19
Faulting process ID: 0x4214
Faulting application start time: 0x01da53c090794026
Faulting application path: D:\Vintagestory\Vintagestory.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report ID: 62061279-4b49-4007-adda-c5380d8bcfe6
Faulting package full name: 
Faulting package-relative application ID:  }

**Comment by WickedSchnitzel** [comment]
a song that was played when one of the crashes occured:
[Beethoven_-_Symphony_No_5.zip](https://github.com/Quacksol/VSInstruments/files/14151490/Beethoven_-_Symphony_No_5.zip)
