### ISSUE TITLE
System.NullReferenceException in 1.19.3 modded mp

### ISSUE THREAD

**Issue by WickedSchnitzel** [Quacksol/VSInstruments#6]
Running on 64 bit Windows 10.0.19045.0 with 32723 MB RAM
Game Version: v1.19.3 (Stable)
02.02.2024 16:29:19: Critical error occurred in the following mod: vsinstruments@1.2.5
Loaded Mods: weaponpacka@1.3.1, bettercrates@1.7.0, Ceramos@0.4.3, chiseltools@1.10.1, cobbgm@1.0.1, extrachests@1.8.0, fixedpaths@1.0.1, flourbags@1.0.2, giantgouramis@1.0.2, ClaimsRadar@1.1.0, millwright@1.1.4, moreicons_cs@1.1.0, peacockbasses@1.1.2, primitivesurvival@3.4.5, spyglass@0.5.0, Swordz@1.1.4, thecritterpack@0.8.3, translocatorengineeringredux@1.4.9, truesunfishes@1.1.2, game@1.19.3, alphaweaponpackfix@1.0.0, ancienttools@1.5.12, barbershop@0.4.0, beehivekiln@1.5.1, betterjonasdevices@1.1.0, betterruins@0.3.2, carryon@1.7.4, commonlib@2.3.2, fairplayguardian@1.1.6, furniturelibrary@1.0.11, herbarium@1.0.4, icecold@0.5.1, sailboat@1.2.7, meteoricexpansion@1.2.5, morepiles@1.5.0, moreplaster@1.0.1, petai@2.2.3, rivers@2.3.0, simplestep@1.1.4, steadycam@1.2.0, stonebakeoven@1.1.3, tentbag@1.0.3, th3dungeon@0.2.1-rc.1, vinconomy@0.2.1, creative@1.19.3, vsinstruments@1.2.5, vsquest@1.2.0, survival@1.19.3, workbenchexpansion@1.8.0, xlib119@0.7.4-dev.119, awearablelight@1.1.1, cob2@1.5.6, cobserver@1.0.0, em@2.5.0, outerspacetunesmaster@1.0.0, outerspacetunesvolume1@1.0.0, outerspacetunesvolume2@1.0.0, playercorpse@1.9.0, rifteye@0.3.4, simplewinddirection@1.0.2, stonequarry@3.2.1, wildcraftfruit@1.0.1, wolftaming@2.0.2, xskills119@0.7.5-dev.1191, bricklayers@2.5.0-pre.2, cob@1.5.9, vsvillagecob@0.1.8
System.NullReferenceException: Object reference not set to an instance of an object.
   at instruments.InstrumentModClient.ParseServerPacket(ABCUpdateFromServer serverPacket)
   at Vintagestory.Client.NoObf.NetworkChannel.<>c__DisplayClass12_0`1.<SetMessageHandler>b__0(Packet_CustomPacket p) in VintagestoryLib\Client\API\NetworkChannel.cs:line 74
   at Vintagestory.Client.NoObf.NetworkAPI.HandleCustomPacket(Packet_Server packet) in VintagestoryLib\Client\API\NetworkAPI.cs:line 95
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 769
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 200
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 675
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 650
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 318
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries for Vintagestory.exe, the latest 2
==================================
{ TimeGenerated = 02.02.2024 15:29:25, Site = , Source = Application Error, Message = Name der fehlerhaften Anwendung: Vintagestory.exe, Version: 1.19.3.0, Zeitstempel: 0x65310000
Name des fehlerhaften Moduls: KERNELBASE.dll, Version: 10.0.19041.3930, Zeitstempel: 0x9141f979
Ausnahmecode: 0xe0434352
Fehleroffset: 0x000000000002cf19
ID des fehlerhaften Prozesses: 0x5eac
Startzeit der fehlerhaften Anwendung: 0x01da55dd0f4635b8
Pfad der fehlerhaften Anwendung: C:\Users\Kai\AppData\Roaming\Vintagestory\Vintagestory.exe
Pfad des fehlerhaften Moduls: C:\WINDOWS\System32\KERNELBASE.dll
Berichtskennung: a8db6754-6ea7-4e2b-a8a1-e06d9b764067
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist:  }
--------------
{ TimeGenerated = 02.02.2024 10:42:41, Site = , Source = Application Error, Message = Name der fehlerhaften Anwendung: Vintagestory.exe, Version: 1.19.3.0, Zeitstempel: 0x65310000
Name des fehlerhaften Moduls: openal32.dll, Version: 1.23.0.0, Zeitstempel: 0x63dd31ad
Ausnahmecode: 0x40000015
Fehleroffset: 0x00000000000df046
ID des fehlerhaften Prozesses: 0x2734
Startzeit der fehlerhaften Anwendung: 0x01da55bc16003dc9
Pfad der fehlerhaften Anwendung: C:\Users\Kai\AppData\Roaming\Vintagestory\Vintagestory.exe
Pfad des fehlerhaften Moduls: C:\Users\Kai\AppData\Roaming\Vintagestory\Lib\openal32.dll
Berichtskennung: 2155313c-f7bf-42b4-8fd7-63899d5c48e6
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist:  }

**Comment by Quacksol** [comment]
Hi,
do you have any more info about the crash - were you connecting to the server, starting/midway through a song, or was someone else playing?
How easy is it for you to reproduce?

**Comment by WickedSchnitzel** [comment]
I was just standing there as it crashed, not sure if anyone was playing an instrument, did not hear anything and i believe no one was nearby.
